### ISSUE TITLE
MySQL 8 Support

### ISSUE THREAD

**Issue by amsclark** [openadvocate/dlaw7#1]
This isn't so much an "issue" as I have no idea what the development roadmap of DLAW is and whether the project maintainers intend to support newer versions of MySQL, but I had difficulty installing DLAW 7 on a newer Linux machine as some distribution repositories are now defaulting to MySQL 8, and DLAW 7 does not appear to be compatible with MySQL 8 and throws errors during the install process.

I found that this https://www.reinisfischer.com/drupal-7-fix-sqlstate42000-syntax-error-or-access-violation-1231-variable-sqlmode-cant-be-set-value resource was helpful and that the sample database.inc worked as a drop-in replacement for /includes/database/mysql/database.inc to enable MySQL 8 compatibility.

Hopefully this information helps somebody.

**Comment by kikim792** [comment]
Hi Alex,

Yes, indeed your post can help others for sure. As we are working on the next major version of DLAW, I am not sure if we'd have the capacity to keep the old code up to date. Nevertheless, we'll keep the issue in mind to have better MySQL support in the new version.

Thanks!
